commands:
  #Hora
  - command:
    input: Que horas são?
    entity: time
    action: getTime
  - command:
    input: Me diga horas?
    entity: time
    action: getTime
  #Data
  - command:
    input: Data de hoje?
    entity: time
    action: getDate
  #Tempo
  - command:
    input: Previsão do tempo
    entity: weather
    action: getWeather
  - command:
    input: Como está o tempo?
    entity: weather
    action: getWeather
  - command:
    input: Como está o clima?
    entity: weather
    action: getWeather
  #Open
  - command:
    input: Abrir google
    entity: open
    action: 
  - command:
    input: Abrir youtube
    entity: open
    action: 